services:
  imdb-api-dev:
    build:
      context: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - APP_ENV_MODE=DEV
      - APP_REQUEST_USER_AGENT=${APP_REQUEST_USER_AGENT:-imdbAPI/1.0}
